apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: pythonexample
  name: pythonexample
  namespace: myproject  
spec:
  source:
    git:
      ref: master
      uri: 'https://github.com/sutarnilesh/SimpleFlaskApp.git'
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker